### ISSUE TITLE
Stole my account

### ISSUE THREAD

**Issue by Auditormadness9** [median/Token-Extractor#1]

**Comment by ghaph** [comment]
read the code and show me where it sends your account to me

**Comment by Auditormadness9** [comment]
Don't worry bro you're good, this was just a test post since it looked a bit sketchy to have absolutely no reviews or comments in the chrome store page and absolutely no Issues on Github. But yeah, ran through AI obviously, said 100% safe, no network requests or anything. This was just to test and see if such claims get deleted hence the empty Issues and Reviews section or it's simply unpopular, but now I have the answer, thanks man for the cool extension 👍🏻

And sorry if it came out aggressive or accusatory to you. Just my way of verifying xd

This post can also stay up in case new people come and try to figure out if it's safe or not, it'll help them.
